[project]
name = "startgg-tools"
version = "0.1.0"
description = "Tiny ass scripts for startgg."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
]

[project.scripts]
startgg-tools = "startggtools:entry"

[dependency-groups]
dev = []
